stages:
  data_load:
    cmd: python -m src.stages.data_load --config=params.yaml
    deps:
    - src/stages/data_load.py
    params:
    - base
    - data_load
    outs:
    - data/raw/iris.csv
  featurize:
    cmd: python -m src.stages.featurize --config=params.yaml
    deps:
    - data/raw/iris.csv
    - src/stages/featurize.py
    params:
    - base
    - featurize
    outs:
    - data/processed/featured_iris.csv
  data_split:
    cmd: python -m src.stages.data_split --config=params.yaml
    deps:
    - data/processed/featured_iris.csv
    - src/stages/data_split.py
    params:
    - base
    - data_split
    - featurize
    outs:
    - data/processed/test_iris.csv
    - data/processed/train_iris.csv
  train:
    cmd: python -m src.stages.train --config=params.yaml
    deps:
    - data/processed/train_iris.csv
    - src/stages/train.py
    params:
    - base
    - train
    outs:
    - models/model.joblib
  evaluate:
    cmd: python -m src.stages.evaluate --config=params.yaml
    deps:
      - data/processed/test_iris.csv
      - src/stages/evaluate.py
      - models/model.joblib
    params:
      - evaluate
    outs:
      - reports/metrics.json
      - reports/confusion_matrix.png
